FROM java:8
ADD /target/PREMIUM-SERVICE-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8087
ENV JAVA_OPTS="-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n"
RUN sh -c 'touch /app.jar'
RUN chmod 777 /app.jar
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=dev -jar /app.jar" ]


# FROM mongo:latest
# ENV MONGO_INITDB_ROOT_USERNAME devadmin
# ENV MONGO_INITDB_ROOT_PASSWORD devadmin
# ENV MONGO_INITDB_DATABASE BAGUS
# COPY mongo-init.js /docker-entrypoint-initdb.d/